@subdominio=idatec02-saluda.onrender.com

GET https://{{subdominio}}/saludo


###
GET https://{{subdominio}}/saludo?name=Zuriel

###

GET https://{{subdominio}}/demo/all

###

POST https://{{subdominio}}/demo/add
Content-Type: application/x-www-form-urlencoded

name=Zuriel&email=zuriel6@idat.edu.pe

###
DELETE https://{{subdominio}}.com/demo/del 
Content-Type: application/x-www-form-urlencoded