##GET http://localhost:8080/saludo

GET https://idatec02-saluda.onrender.com/saludo


###
GET https://idatec02-saluda.onrender.com/saludo?name=Zuriel

###

GET https://idatec02-saluda.onrender.com/demo/all

###

POST https://idatec02-saluda.onrender.com/demo/add
Content-Type: application/x-www-form-urlencoded

name=Zuriel&email=zuriel6@idat.edu.pe